// This file can be included several times.

#ifndef MACRO_CONFIG_INT
#error "The config macros must be defined"
#define MACRO_CONFIG_INT(Name, ScriptName, Def, Min, Max, Save, Desc) ;
#define MACRO_CONFIG_COL(Name, ScriptName, Def, Save, Desc) ;
#define MACRO_CONFIG_STR(Name, ScriptName, Len, Def, Save, Desc) ;
#endif

MACRO_CONFIG_INT(AeMusicPlayer, ae_music_player, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show the Aether music timer panel")
MACRO_CONFIG_INT(AeMusicDynamicColor, ae_music_dynamic_color, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Derive the music panel background from cover artwork")
MACRO_CONFIG_COL(AeMusicBackgroundColor, ae_music_background_color, 1710618, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Static music panel background color")
MACRO_CONFIG_INT(AeMusicOpacity, ae_music_opacity, 75, 10, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music panel opacity")
MACRO_CONFIG_INT(AeMusicScale, ae_music_scale, 100, 50, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music panel size")
MACRO_CONFIG_INT(AeMusicFreezeCounter, ae_music_freeze_counter, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show frozen tees count inside the music panel")
MACRO_CONFIG_INT(AeMusicMediaTitle, ae_music_media_title, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show current media title inside the music panel")
MACRO_CONFIG_INT(AeMusicTimeline, ae_music_timeline, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show current media timeline inside the music panel")
MACRO_CONFIG_INT(AeMusicVisualizer, ae_music_visualizer, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show process-specific five-band audio visualization")
MACRO_CONFIG_INT(AeMusicVisualizerStyle, ae_music_visualizer_style, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music visualizer style: bars or mountain")
MACRO_CONFIG_INT(AeMusicVisualizerGlow, ae_music_visualizer_glow, 45, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music visualizer glow amount")
MACRO_CONFIG_INT(AeMusicVisualizerSensitivity, ae_music_visualizer_sensitivity, 100, 50, 1500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music visualizer sensitivity")
MACRO_CONFIG_INT(AeMusicVisualizerAutoGain, ae_music_visualizer_auto_gain, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Boost real low-volume captured audio for the music visualizer")
MACRO_CONFIG_INT(AeMusicOffsetX, ae_music_offset_x, 0, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music panel horizontal offset from top center")
MACRO_CONFIG_INT(AeMusicOffsetY, ae_music_offset_y, 0, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music panel vertical offset from top center")

MACRO_CONFIG_INT(AeCustomMenuTheme, ae_custom_menu_theme, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use a custom PNG as the main menu background")
MACRO_CONFIG_STR(AeCustomMenuThemeImage, ae_custom_menu_theme_image, 128, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom menu theme PNG name or path")
MACRO_CONFIG_INT(AeCustomMenuThemeDim, ae_custom_menu_theme_dim, 22, 0, 80, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Darken the custom menu theme image")
MACRO_CONFIG_INT(AeMenuThemeOverride, ae_menu_theme_override, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use the coded Aether main menu theme override")

MACRO_CONFIG_INT(AeKeystrokes, ae_keystrokes, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show compact movement and mouse input keys")
MACRO_CONFIG_INT(AeKeystrokesOffsetX, ae_keystrokes_offset_x, 0, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Keystrokes overlay horizontal offset from the lower center")
MACRO_CONFIG_INT(AeKeystrokesOffsetY, ae_keystrokes_offset_y, 86, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Keystrokes overlay vertical offset from the lower center")
MACRO_CONFIG_INT(AeKeystrokesScale, ae_keystrokes_scale, 100, 50, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Keystrokes overlay size")
MACRO_CONFIG_INT(AeKeystrokesHorizontal, ae_keystrokes_horizontal, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use horizontal keystrokes layout")
MACRO_CONFIG_INT(AeKeystrokesShowJump, ae_keystrokes_show_jump, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show jump key in keystrokes")
MACRO_CONFIG_INT(AeKeystrokesShowFire, ae_keystrokes_show_fire, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show M1 key in keystrokes")
MACRO_CONFIG_INT(AeKeystrokesJumpLabel, ae_keystrokes_jump_label, 1, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Keystrokes jump label: 0 jump, 1 line, 2 space")

MACRO_CONFIG_INT(AeInputVisualizer, ae_input_visualizer, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show a compact input history visualizer")
MACRO_CONFIG_INT(AeInputVisualizerPaused, ae_input_visualizer_paused, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pause the input visualizer flow")
MACRO_CONFIG_INT(AeInputVisualizerFlow, ae_input_visualizer_flow, 280, 40, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Input visualizer scroll speed")
MACRO_CONFIG_INT(AeInputVisualizerShowLocal, ae_input_visualizer_show_local, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show local keyboard and mouse input")
MACRO_CONFIG_INT(AeInputVisualizerMouse, ae_input_visualizer_mouse, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Include mouse buttons in the input visualizer")
MACRO_CONFIG_INT(AeInputVisualizerShowJump, ae_input_visualizer_show_jump, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Include the jump lane in the input visualizer")
MACRO_CONFIG_INT(AeInputVisualizerShowFire, ae_input_visualizer_show_fire, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Include the M1 lane in the input visualizer")
MACRO_CONFIG_INT(AeInputVisualizerLabels, ae_input_visualizer_labels, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show lane labels in the input visualizer")
MACRO_CONFIG_INT(AeInputVisualizerSpectatedInput, ae_input_visualizer_spectated_input, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use the followed player's inputs while spectating or watching demos")
MACRO_CONFIG_INT(AeInputVisualizerHookMarkers, ae_input_visualizer_hook_markers, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw hook press/release markers over the movement lanes")
MACRO_CONFIG_INT(AeInputVisualizerVertical, ae_input_visualizer_vertical, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use vertical input visualizer layout")
MACRO_CONFIG_INT(AeInputVisualizerBackground, ae_input_visualizer_background, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw the input visualizer panel background")
MACRO_CONFIG_INT(AeInputVisualizerSharpCorners, ae_input_visualizer_sharp_corners, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use sharp input visualizer corners")
MACRO_CONFIG_INT(AeInputVisualizerLength, ae_input_visualizer_length, 100, 50, 250, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Input visualizer history length")
MACRO_CONFIG_INT(AeInputVisualizerThickness, ae_input_visualizer_thickness, 100, 40, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Input visualizer lane thickness")
MACRO_CONFIG_INT(AeInputVisualizerOpacity, ae_input_visualizer_opacity, 90, 10, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Input visualizer opacity")
MACRO_CONFIG_COL(AeInputVisualizerColorLeft, ae_input_visualizer_color_left, 0xF2E6C738, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Input visualizer left lane color")
MACRO_CONFIG_COL(AeInputVisualizerColorRight, ae_input_visualizer_color_right, 0xF24582E6, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Input visualizer right lane color")
MACRO_CONFIG_COL(AeInputVisualizerColorJump, ae_input_visualizer_color_jump, 0xF2FFFFFF, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Input visualizer jump lane color")
MACRO_CONFIG_COL(AeInputVisualizerColorFire, ae_input_visualizer_color_fire, 0xF24FC778, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Input visualizer fire lane color")
MACRO_CONFIG_COL(AeInputVisualizerColorHook, ae_input_visualizer_color_hook, 0xF2AB63E6, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Input visualizer hook lane color")
MACRO_CONFIG_INT(AeInputVisualizerOffsetX, ae_input_visualizer_offset_x, 0, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Input visualizer horizontal offset from the lower center")
MACRO_CONFIG_INT(AeInputVisualizerOffsetY, ae_input_visualizer_offset_y, 132, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Input visualizer vertical offset from the lower center")
MACRO_CONFIG_INT(AeInputVisualizerScale, ae_input_visualizer_scale, 100, 50, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Input visualizer HUD size")

MACRO_CONFIG_INT(AeSessionStats, ae_session_stats, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show compact session statistics")
MACRO_CONFIG_INT(AeSessionStatsShowTime, ae_session_stats_show_time, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show elapsed session time")
MACRO_CONFIG_INT(AeSessionStatsShowMap, ae_session_stats_show_map, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Deprecated; map name is not shown in session statistics")
MACRO_CONFIG_INT(AeSessionStatsOffsetX, ae_session_stats_offset_x, 0, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Session stats horizontal offset from the upper left")
MACRO_CONFIG_INT(AeSessionStatsOffsetY, ae_session_stats_offset_y, 76, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Session stats vertical offset from the top")
MACRO_CONFIG_INT(AeSessionStatsScale, ae_session_stats_scale, 100, 50, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Session stats HUD size")

MACRO_CONFIG_INT(AeStabilityTrainer, ae_stability_trainer, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show velocity stability trainer overlay")
MACRO_CONFIG_INT(AeStabilityTrainerShowBar, ae_stability_trainer_show_bar, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw the stability trainer velocity bar")
MACRO_CONFIG_INT(AeStabilityTrainerShowStability, ae_stability_trainer_show_stability, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw the stability percentage")
MACRO_CONFIG_INT(AeStabilityTrainerVelocityScope, ae_stability_trainer_velocity_scope, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use full 2D velocity for quality instead of horizontal velocity only")
MACRO_CONFIG_INT(AeStabilityTrainerColorize, ae_stability_trainer_colorize, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Colorize trainer feedback by quality")
MACRO_CONFIG_COL(AeStabilityTrainerColor, ae_stability_trainer_color, 0xFFF0E050, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Solid stability trainer color")
MACRO_CONFIG_INT(AeStabilityTrainerAverageTicks, ae_stability_trainer_average_ticks, 12, 1, 40, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Stability quality smoothing ticks")
MACRO_CONFIG_INT(AeStabilityTrainerBarGlide, ae_stability_trainer_bar_glide, 8, 8, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Velocity bar visual follow speed")
MACRO_CONFIG_INT(AeStabilityTrainerMinSpeed, ae_stability_trainer_min_speed, 600, 0, 600, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blend out when speed is below this value")
MACRO_CONFIG_INT(AeStabilityTrainerVelocityScale, ae_stability_trainer_velocity_scale, 800, 50, 800, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Velocity reference scale")
MACRO_CONFIG_INT(AeStabilityTrainerSharpCorners, ae_stability_trainer_sharp_corners, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use sharp trainer bar corners")
MACRO_CONFIG_INT(AeStabilityTrainerBarThickness, ae_stability_trainer_bar_thickness, 100, 50, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trainer bar thickness")
MACRO_CONFIG_INT(AeStabilityTrainerTrackWidth, ae_stability_trainer_track_width, 100, 50, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trainer track width")
MACRO_CONFIG_INT(AeStabilityTrainerBlockWidth, ae_stability_trainer_block_width, 100, 40, 150, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Trainer moving block width")
MACRO_CONFIG_INT(AeStabilityTrainerSpectate, ae_stability_trainer_spectate, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show stability trainer for spectated players and demos")
MACRO_CONFIG_INT(AeStabilityTrainerOffsetX, ae_stability_trainer_offset_x, 0, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Stability trainer horizontal offset from the lower center")
MACRO_CONFIG_INT(AeStabilityTrainerOffsetY, ae_stability_trainer_offset_y, 74, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Stability trainer vertical offset from the lower center")
MACRO_CONFIG_INT(AeStabilityTrainerScale, ae_stability_trainer_scale, 100, 50, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Stability trainer HUD size")

MACRO_CONFIG_INT(AeAutoTeamLock, ae_auto_team_lock, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Automatically lock a DDNet team after joining")
MACRO_CONFIG_INT(AeAutoTeamLockDelay, ae_auto_team_lock_delay, 3, 0, 60, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Seconds to wait before locking a joined DDNet team")

MACRO_CONFIG_INT(AeBlockAwareness, ae_block_awareness, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Aether block awareness helpers")
MACRO_CONFIG_INT(AeBlockColorPlayers, ae_block_color_players, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Color block players by warlist category")
MACRO_CONFIG_INT(AeBlockAlliesKeepRealSkins, ae_block_allies_keep_real_skins, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Keep ally skins unchanged while coloring block players")
MACRO_CONFIG_INT(AeBlockColorNames, ae_block_color_names, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Color nameplates and scoreboard names by block category")
MACRO_CONFIG_INT(AeBlockNeutralColorPlayers, ae_block_neutral_color_players, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Color neutral players who are not in block warlist")
MACRO_CONFIG_INT(AeBlockNeutralColorNames, ae_block_neutral_color_names, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Color neutral nameplates and scoreboard names")
MACRO_CONFIG_INT(AeBlockNeutralKeepRealSkins, ae_block_neutral_keep_real_skins, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Keep neutral skins unchanged while coloring neutral players")
MACRO_CONFIG_INT(AeBlockEnemySize, ae_block_enemy_size, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Visually enlarge enemy tees")
MACRO_CONFIG_INT(AeBlockSaveDetector, ae_block_save_detector, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Detect players who save you from freeze")
MACRO_CONFIG_INT(AeBlockSavePopup, ae_block_save_popup, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show a helper/ally popup after a detected save")
MACRO_CONFIG_INT(AeBlockFreezeBars, ae_block_freeze_bars, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show block awareness freeze bars with milliseconds")
MACRO_CONFIG_INT(AeBlockLocalFreezeOverlay, ae_block_local_freeze_overlay, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show a large local freeze timing overlay")
MACRO_CONFIG_INT(AeBlockAllyFreezeAlert, ae_block_ally_freeze_alert, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Alert when allies/helpers are frozen")
MACRO_CONFIG_INT(AeBlockEnemyCountHud, ae_block_enemy_count_hud, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show nearby enemy count HUD")
MACRO_CONFIG_INT(AeBlockHideEnemyEmotes, ae_block_hide_enemy_emotes, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide enemy overhead emotes")
MACRO_CONFIG_INT(AeBlockForceEnemyEyes, ae_block_force_enemy_eyes, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Force enemy tee eyes to a readable default")
MACRO_CONFIG_INT(AeBlockDangerZone, ae_block_danger_zone, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pulse when too many enemies are nearby")
MACRO_CONFIG_INT(AeBlockDangerRadius, ae_block_danger_radius, 420, 160, 900, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Danger zone radius in game units")
MACRO_CONFIG_INT(AeBlockDangerCount, ae_block_danger_count, 3, 2, 8, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enemy count needed for danger zone")
MACRO_CONFIG_INT(AeBlockEnemyScanBlocks, ae_block_enemy_scan_blocks, 48, 5, 80, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enemy count HUD scan radius in blocks")
MACRO_CONFIG_INT(AeBlockDetector, ae_block_detector, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Detect probable players who blocked or killed you")
MACRO_CONFIG_INT(AeBlockDetectorPopup, ae_block_detector_popup, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show an enemy popup after probable block/kill")
MACRO_CONFIG_COL(AeBlockEnemyColor, ae_block_enemy_color, 0xFF3A3A, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Block awareness enemy color")
MACRO_CONFIG_COL(AeBlockHelperColor, ae_block_helper_color, 0xFFE060, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Block awareness helper color")
MACRO_CONFIG_COL(AeBlockAllyColor, ae_block_ally_color, 0x58E875, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Block awareness ally color")
MACRO_CONFIG_COL(AeBlockUnknownColor, ae_block_unknown_color, 0xD8D8D8, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Block awareness unknown player color")
MACRO_CONFIG_COL(AeBlockNeutralColor, ae_block_neutral_color, 0xD8D8D8, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Block awareness neutral player color")
MACRO_CONFIG_INT(AeBlockEnemyScale, ae_block_enemy_scale, 115, 100, 150, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enemy visual tee scale percent")
MACRO_CONFIG_INT(AeBlockHelperScale, ae_block_helper_scale, 105, 100, 150, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Helper visual tee scale percent")
MACRO_CONFIG_INT(AeBlockAllyScale, ae_block_ally_scale, 100, 100, 150, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Ally visual tee scale percent")
MACRO_CONFIG_INT(AeBlockNeutralScale, ae_block_neutral_scale, 100, 80, 150, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Neutral visual tee scale percent")
MACRO_CONFIG_INT(AeBlockEnemyNameOpacity, ae_block_enemy_name_opacity, 100, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enemy nameplate opacity percent")
MACRO_CONFIG_INT(AeBlockHelperNameOpacity, ae_block_helper_name_opacity, 100, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Helper nameplate opacity percent")
MACRO_CONFIG_INT(AeBlockAllyNameOpacity, ae_block_ally_name_opacity, 100, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Ally nameplate opacity percent")
MACRO_CONFIG_INT(AeBlockNeutralNameOpacity, ae_block_neutral_name_opacity, 100, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Neutral nameplate opacity percent")

MACRO_CONFIG_INT(AeFocusMode, ae_focus_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide nonessential HUD overlays for focused play")
MACRO_CONFIG_INT(AeFocusModeHideAllUi, ae_focus_mode_hide_all_ui, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide all UI while Focus Mode is active")
MACRO_CONFIG_INT(AeFocusModeHideNameplates, ae_focus_mode_hide_nameplates, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide nameplates while Focus Mode is active")
MACRO_CONFIG_INT(AeFocusModeKeepMusicPlayer, ae_focus_mode_keep_music_player, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Keep music player visible while Focus Mode hides all UI")
MACRO_CONFIG_INT(AeLoadingThemeBackground, ae_loading_theme_background, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show the menu theme background on loading screens")
MACRO_CONFIG_INT(AeBadges, ae_badges, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Aether client badges")
MACRO_CONFIG_INT(AeBadgesNameplates, ae_badges_nameplates, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show Aether badges in nameplates")
MACRO_CONFIG_INT(AeBadgesScoreboard, ae_badges_scoreboard, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show Aether badges in the scoreboard")
MACRO_CONFIG_INT(AeBadgesClientOnly, ae_badges_client_only, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Only show automatic client identity badges")
MACRO_CONFIG_INT(AeBadgesRefreshSeconds, ae_badges_refresh_seconds, 300, 30, 3600, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether badge API refresh interval")
MACRO_CONFIG_STR(AeBadgesApiUrl, ae_badges_api_url, 256, "https://aetherclient-api-production.up.railway.app", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether badge API base URL")
MACRO_CONFIG_INT(AeKogPointsScoreboard, ae_kog_points_scoreboard, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show KoG points in the scoreboard player popup on KoG servers")
MACRO_CONFIG_INT(AeNotifications, ae_notifications, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show Aether notification toasts")
MACRO_CONFIG_INT(AeNotificationsUpdateCheck, ae_notifications_update_check, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show update notifications when a new Aether release is available")
MACRO_CONFIG_INT(AeNotificationsCommandPalette, ae_notifications_command_palette, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show command palette action notifications")
MACRO_CONFIG_INT(AeNotificationsSessionMarkers, ae_notifications_session_markers, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show session marker notifications")
MACRO_CONFIG_INT(AeNotificationsRollbackDemo, ae_notifications_rollback_demo, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show rollback demo notifications instead of chat echoes")
MACRO_CONFIG_INT(AeCommandPalette, ae_command_palette, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable the Aether command palette")
MACRO_CONFIG_INT(AeSessionMarkers, ae_session_markers, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Aether demo/session markers")
MACRO_CONFIG_INT(AeSessionMarkerAutoFreeze, ae_session_marker_auto_freeze, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Automatically add a demo marker when the local tee freezes")
MACRO_CONFIG_INT(AeSessionMarkerAutoDeath, ae_session_marker_auto_death, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Deprecated: migrated to ae_session_marker_auto_freeze")
MACRO_CONFIG_STR(AeClanId, ae_clan_id, 96, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Stored Aether clan id")
MACRO_CONFIG_STR(AeClanSecret, ae_clan_secret, 128, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Stored Aether clan membership secret")
MACRO_CONFIG_STR(AeClanGeneralId, ae_clan_general_id, 96, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Stored Aether general clan id")
MACRO_CONFIG_STR(AeClanGeneralSecret, ae_clan_general_secret, 128, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Stored Aether general clan membership secret")
MACRO_CONFIG_STR(AeClanKogId, ae_clan_kog_id, 96, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Stored Aether KoG clan id")
MACRO_CONFIG_STR(AeClanKogSecret, ae_clan_kog_secret, 128, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Stored Aether KoG clan membership secret")
MACRO_CONFIG_INT(AeChatBubbles, ae_chat_bubbles, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show player chat messages above tees")
MACRO_CONFIG_INT(AeChatBubblesDuration, ae_chat_bubbles_duration, 4, 2, 8, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Seconds to show chat bubbles")
MACRO_CONFIG_INT(AeChatBubblesOpacity, ae_chat_bubbles_opacity, 85, 20, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Chat bubble opacity")
MACRO_CONFIG_INT(AeChatBubblesWidth, ae_chat_bubbles_width, 140, 80, 220, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum chat bubble width")
MACRO_CONFIG_INT(AeChatBubblesVisibleOnly, ae_chat_bubbles_visible_only, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Only show chat bubbles for tees visible on screen")
MACRO_CONFIG_INT(AeChatBubblesColoredMessages, ae_chat_bubbles_colored_messages, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Color chat bubble text by team and mentions")
MACRO_CONFIG_INT(AeChatBubblesStackCount, ae_chat_bubbles_stack_count, 4, 1, 4, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum chat bubbles per player")
MACRO_CONFIG_INT(AeChatBubblesShowOwnLive, ae_chat_bubbles_show_own_live, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show your current chat draft above your tee")
MACRO_CONFIG_INT(AeChatBubblesShowOwnSent, ae_chat_bubbles_show_own_sent, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show your sent chat messages above your tee")
MACRO_CONFIG_INT(AeChatBubblesWhispers, ae_chat_bubbles_whispers, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show whisper messages as chat bubbles")
MACRO_CONFIG_INT(AeSilentTyping, ae_silent_typing, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Do not send the chat typing flag to the server")
MACRO_CONFIG_INT(AeSnapTap, ae_snap_tap, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use the last pressed left/right key when both directions are held")
MACRO_CONFIG_INT(AeGoresMode, ae_gores_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Aether Gores Mode")
MACRO_CONFIG_INT(AeGoresModeDisableIfWeapons, ae_gores_mode_disable_weapons, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Disable Gores Mode while holding shotgun, grenade or laser")
MACRO_CONFIG_INT(AeFastInput, ae_fast_input, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Aether fast input prediction")
MACRO_CONFIG_INT(AeFastInputMode, ae_fast_input_mode, 1, 0, 6, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether fast input mode: 0/1 adaptive, 2 saiko plus, 3 tclient, 4 control, 5 lewn plus, 6 zenish plus")
MACRO_CONFIG_INT(AeFastInputMovementAmount, ae_fast_input_movement_amount, 30, 0, 50, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether fast input movement prediction amount")
MACRO_CONFIG_INT(AeFastInputActionAmount, ae_fast_input_action_amount, 38, 0, 50, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether fast input hook and fire prediction amount")
MACRO_CONFIG_INT(AeFastInputControlResponse, ae_fast_input_control_response, 27, 0, 50, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether control input response amount")
MACRO_CONFIG_INT(AeFastInputControlStability, ae_fast_input_control_stability, 58, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether control input stability amount")
MACRO_CONFIG_INT(AeFastInputControlCorrection, ae_fast_input_control_correction, 62, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether control input correction sharpness")
MACRO_CONFIG_INT(AeFastInputControlOthers, ae_fast_input_control_others, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply Aether control input offset to other tees")
MACRO_CONFIG_INT(AeFastInputControlPingAssist, ae_fast_input_control_ping_assist, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply Control-only prediction-time render follow adjustment")
MACRO_CONFIG_INT(AeFastInputControlInteractionAssist, ae_fast_input_control_interaction_assist, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply Control-only interaction render smoothing")
MACRO_CONFIG_INT(AeFastInputControlInteractionStrength, ae_fast_input_control_interaction_strength, 50, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether control input interaction smoothing strength")
MACRO_CONFIG_INT(AeSaikoPlusAmount, ae_saiko_plus_amount, 0, 0, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Saiko plus amount in 0.01 ticks")
MACRO_CONFIG_INT(AeSaikoPlusOthers, ae_saiko_plus_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply Saiko plus fast input to other tees")
MACRO_CONFIG_INT(AeLewnPlusAmount, ae_lewn_plus_amount, 140, 100, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Lewn plus amount in 0.01 ticks")
MACRO_CONFIG_INT(AeLewnPlusCorrection, ae_lewn_plus_correction, 75, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Lewn plus render correction sharpness")
MACRO_CONFIG_INT(AeLewnPlusOthers, ae_lewn_plus_others, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply Lewn plus fast input to other tees")
MACRO_CONFIG_INT(AeZenishPlusAmount, ae_zenish_plus_amount, 100, 100, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Zeni$h plus amount in 0.01 ticks")
MACRO_CONFIG_INT(AeZenishPlusCorrection, ae_zenish_plus_correction, 30, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Zeni$h plus render correction softness")
MACRO_CONFIG_INT(AeZenishPlusOthers, ae_zenish_plus_others, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply Zeni$h plus fast input to other tees")
MACRO_CONFIG_INT(AeFastInputAdaptiveOthers, ae_fast_input_adaptive_others, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply adaptive fast input movement offset to other tees")
MACRO_CONFIG_INT(AeFastInputAdaptiveOthersStyle, ae_fast_input_adaptive_others_style, 1, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Adaptive fast input other tee feel: 0 smooth, 1 precision, 2 aggressive")
MACRO_CONFIG_INT(AeFastInputAdaptiveOthersAmount, ae_fast_input_adaptive_others_amount, 135, 0, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Adaptive fast input other tee amount in 0.01 ticks")
MACRO_CONFIG_INT(AeFastInputBrakePriority, ae_fast_input_brake_priority, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Predict A/D reverse direction changes more aggressively")
MACRO_CONFIG_INT(AeFastInputBrakeReleasePriority, ae_fast_input_brake_release_priority, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Predict A/D to neutral changes more aggressively")
MACRO_CONFIG_INT(AeFastInputBrakeAToD, ae_fast_input_brake_a_to_d, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Predict A to D direction changes more aggressively")
MACRO_CONFIG_INT(AeFastInputBrakeDToA, ae_fast_input_brake_d_to_a, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Predict D to A direction changes more aggressively")
MACRO_CONFIG_INT(AeFastInputBrakeAToNone, ae_fast_input_brake_a_to_none, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Predict A to neutral direction changes more aggressively")
MACRO_CONFIG_INT(AeFastInputBrakeDToNone, ae_fast_input_brake_d_to_none, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Predict D to neutral direction changes more aggressively")
MACRO_CONFIG_INT(AeFastInputBrakeAmount, ae_fast_input_brake_amount, 30, 0, 50, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether fast input brake priority prediction amount")
MACRO_CONFIG_INT(AeFastInputBrakeVisualAssist, ae_fast_input_brake_visual_assist, 0, 0, 1, CFGFLAG_CLIENT, "Legacy no-op: old brake visual assist compatibility")
MACRO_CONFIG_INT(AeFastInputSmoothCorrections, ae_fast_input_smooth_corrections, 43, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether fast input correction sharpness")
MACRO_CONFIG_INT(AeFastInputPingAssist, ae_fast_input_ping_assist, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Adjust Aether fast input correction sharpness slightly from prediction time")
MACRO_CONFIG_INT(AeFastInputInteractionAssist, ae_fast_input_interaction_assist, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Smooth Aether fast input render corrections during hook, drag and freeze-save interactions")
MACRO_CONFIG_INT(AeFastInputInteractionStrength, ae_fast_input_interaction_strength, 50, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether fast input interaction smoothing strength")
MACRO_CONFIG_INT(AeFastInputAutoMargin, ae_fast_input_auto_margin, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use fast input amount as a prediction margin floor")
MACRO_CONFIG_INT(AeInputLagGuard, ae_input_lag_guard, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Reduce isolated fast input timing spikes and other-tee jitter")
MACRO_CONFIG_INT(AeFastInputDummy, ae_fast_input_dummy, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply Aether fast input to controlled dummy inputs")
MACRO_CONFIG_INT(AeFastInputDebug, ae_fast_input_debug, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show Aether fast input debug information")
MACRO_CONFIG_INT(AeFastSpec, ae_fast_spec, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Queue spectate requests at a safe cadence")
MACRO_CONFIG_INT(AeFreezeFailSound, ae_freeze_fail_sound, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Aether freeze fail sounds")
MACRO_CONFIG_INT(AeFreezeFailSoundLocal, ae_freeze_fail_sound_local, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Play freeze fail sound for your tee and dummy")
MACRO_CONFIG_INT(AeFreezeFailSoundOthers, ae_freeze_fail_sound_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Play freeze fail sound for other tees on your DDRace team")
MACRO_CONFIG_INT(AeFreezeFailSoundTeamLast, ae_freeze_fail_sound_team_last, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Play a sound when you become the last unfrozen tee on your team")
MACRO_CONFIG_STR(AeFreezeFailSoundLocalFile, ae_freeze_fail_sound_local_file, 128, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "File in assets/failsound/ for local freeze fail sound")
MACRO_CONFIG_STR(AeFreezeFailSoundOthersFile, ae_freeze_fail_sound_others_file, 128, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "File in assets/failsound/ for teammate freeze fail sound")
MACRO_CONFIG_STR(AeFreezeFailSoundTeamLastFile, ae_freeze_fail_sound_team_last_file, 128, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "File in assets/failsound/ for team-last freeze fail sound")
MACRO_CONFIG_INT(AeFreezeFailSoundLocalVol, ae_freeze_fail_sound_local_vol, 100, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Volume for local freeze fail sound")
MACRO_CONFIG_INT(AeFreezeFailSoundOthersVol, ae_freeze_fail_sound_others_vol, 100, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Volume for teammate freeze fail sound")
MACRO_CONFIG_INT(AeFreezeFailSoundTeamLastVol, ae_freeze_fail_sound_team_last_vol, 100, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Volume for team-last freeze fail sound")

MACRO_CONFIG_INT(AeSound, ae_sound, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Aether gameplay sound controls")
MACRO_CONFIG_INT(AeSoundLocalHook, ae_sound_local_hook, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Play local hook sounds")
MACRO_CONFIG_INT(AeSoundOthersHook, ae_sound_others_hook, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Play hook sounds from other players")
MACRO_CONFIG_INT(AeSoundOthersHammer, ae_sound_others_hammer, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Play hammer sounds from other players")
MACRO_CONFIG_INT(AeSoundLocalHammer, ae_sound_local_hammer, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Play local hammer swing and hit sounds")
MACRO_CONFIG_INT(AeSoundWeaponSwitch, ae_sound_weapon_switch, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Play local weapon switch sounds")
MACRO_CONFIG_INT(AeSoundOthersWeaponSwitch, ae_sound_others_weapon_switch, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Play weapon switch sounds from other players")
MACRO_CONFIG_INT(AeSoundAirJump, ae_sound_air_jump, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Legacy double jump sounds setting")
MACRO_CONFIG_INT(AeSoundLocalAirJump, ae_sound_local_air_jump, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Play local double jump sounds")
MACRO_CONFIG_INT(AeSoundOthersAirJump, ae_sound_others_air_jump, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Play double jump sounds from other players")
MACRO_CONFIG_INT(AeSoundAirJumpSplitMigrated, ae_sound_air_jump_split_migrated, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Internal migration flag for split double jump sound settings")
MACRO_CONFIG_INT(AeSoundLocalKillRespawn, ae_sound_local_kill_respawn, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Play local kill and respawn sounds")
MACRO_CONFIG_INT(AeSoundOthersKillRespawn, ae_sound_others_kill_respawn, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Play kill and respawn sounds from other players")
MACRO_CONFIG_INT(AeKeyboardSound, ae_keyboard_sound, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Play a short sound while typing in chat")
MACRO_CONFIG_STR(AeKeyboardSoundFile, ae_keyboard_sound_file, 128, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "File in assets/keyboard/ for chat typing sound")
MACRO_CONFIG_INT(AeKeyboardSoundVol, ae_keyboard_sound_vol, 70, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Volume for chat typing sound")

MACRO_CONFIG_INT(AeShowRealHitbox, ae_show_real_hitbox, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show the real character collision box")
MACRO_CONFIG_COL(AeRealHitboxColor, ae_real_hitbox_color, 0xFFFFFF, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Real hitbox marker color")

MACRO_CONFIG_INT(AeNinjaTeePreview, ae_ninja_tee_preview, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show the Aether ninja tee color preview")
MACRO_CONFIG_COL(AeNinjaTeeBodyColor, ae_ninja_tee_body_color, 65408, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLLIGHT, "Aether ninja tee preview body color")
MACRO_CONFIG_COL(AeNinjaTeeFeetColor, ae_ninja_tee_feet_color, 65408, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLLIGHT, "Aether ninja tee preview feet color")

MACRO_CONFIG_INT(AeSweatWeapon, ae_sweat_weapon, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show Aether crystal rifle and sand shotgun beam effects")
MACRO_CONFIG_INT(AeSweatWeaponCustomColors, ae_sweat_weapon_custom_colors, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom Sweat Weapon rifle and shotgun colors")
MACRO_CONFIG_COL(AeSweatWeaponCrystalGlowColor, ae_sweat_weapon_crystal_glow_color, 0x3FE6FF, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Sweat Weapon crystal laser glow color")
MACRO_CONFIG_COL(AeSweatWeaponCrystalCoreColor, ae_sweat_weapon_crystal_core_color, 0xFFFFFF, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Sweat Weapon crystal laser core color")
MACRO_CONFIG_COL(AeSweatWeaponShotgunGlowColor, ae_sweat_weapon_shotgun_glow_color, 0xFFD89A, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Sweat Weapon shotgun glow color")
MACRO_CONFIG_COL(AeSweatWeaponShotgunCoreColor, ae_sweat_weapon_shotgun_core_color, 0xFFFFFF, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Sweat Weapon shotgun core color")
MACRO_CONFIG_COL(AeSweatWeaponEntitiesGlowColor, ae_sweat_weapon_entities_glow_color, 0xB86BFF, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Sweat Weapon entities laser glow color")
MACRO_CONFIG_COL(AeSweatWeaponEntitiesCoreColor, ae_sweat_weapon_entities_core_color, 0xFFFFFF, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Sweat Weapon entities laser core color")
MACRO_CONFIG_INT(AeSweatWeaponGlow, ae_sweat_weapon_glow, 65, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Sweat Weapon glow strength")
MACRO_CONFIG_INT(AeSweatWeaponShine, ae_sweat_weapon_shine, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Animate Sweat Weapon beam shine")
MACRO_CONFIG_INT(AeSweatWeaponShineSpeed, ae_sweat_weapon_shine_speed, 70, 10, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Sweat Weapon shine animation speed")
MACRO_CONFIG_INT(AeSweatWeaponSparkles, ae_sweat_weapon_sparkles, 35, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Sweat Weapon sparkle intensity")
MACRO_CONFIG_INT(AeSweatWeaponElectric, ae_sweat_weapon_electric, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw electric arcs over Sweat Weapon beams")
MACRO_CONFIG_INT(AeSweatWeaponArcDensity, ae_sweat_weapon_arc_density, 60, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Sweat Weapon electric arc density")
MACRO_CONFIG_INT(AeSweatWeaponArcOpacity, ae_sweat_weapon_arc_opacity, 100, 0, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Sweat Weapon electric arc opacity")
MACRO_CONFIG_INT(AeSweatWeaponThickness, ae_sweat_weapon_thickness, 100, 50, 220, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Sweat Weapon laser thickness")
MACRO_CONFIG_INT(AeSweatWeaponEntitiesLaser, ae_sweat_weapon_entities_laser, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply Sweat Weapon style to DDNet entities lasers")

MACRO_CONFIG_INT(AeOrbitAura, ae_orbit_aura, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw an Aether orbit aura around the local tee")
MACRO_CONFIG_INT(AeOrbitAuraIdleOnly, ae_orbit_aura_idle_only, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Only draw orbit aura while the local tee is idle")
MACRO_CONFIG_INT(AeOrbitAuraIdleDelay, ae_orbit_aura_idle_delay, 400, 0, 3000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Milliseconds before idle-only orbit aura fades in")
MACRO_CONFIG_INT(AeOrbitAuraFadeMs, ae_orbit_aura_fade_ms, 260, 0, 1500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Orbit aura fade in and fade out duration")
MACRO_CONFIG_INT(AeOrbitAuraStyle, ae_orbit_aura_style, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Orbit aura style: particles, ring or flame")
MACRO_CONFIG_INT(AeOrbitAuraRadius, ae_orbit_aura_radius, 58, 24, 140, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Orbit aura radius")
MACRO_CONFIG_INT(AeOrbitAuraParticles, ae_orbit_aura_particles, 34, 6, 96, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Orbit aura particle count")
MACRO_CONFIG_INT(AeOrbitAuraAlpha, ae_orbit_aura_alpha, 70, 5, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Orbit aura opacity")
MACRO_CONFIG_INT(AeOrbitAuraSpeed, ae_orbit_aura_speed, 100, 10, 250, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Orbit aura animation speed")
MACRO_CONFIG_INT(AeOrbitAuraSize, ae_orbit_aura_size, 100, 40, 220, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Orbit aura particle size")
MACRO_CONFIG_COL(AeOrbitAuraColor, ae_orbit_aura_color, 0x5CFFD0, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Orbit aura primary color")
MACRO_CONFIG_COL(AeOrbitAuraAccentColor, ae_orbit_aura_accent_color, 0xB5FFF0, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Orbit aura accent color")

MACRO_CONFIG_INT(AeJellyTee, ae_jelly_tee, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Squash and stretch the local tee while moving")
MACRO_CONFIG_INT(AeJellyTeeOthers, ae_jelly_tee_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply Jelly Tee to other players too")
MACRO_CONFIG_INT(AeJellyTeeStrength, ae_jelly_tee_strength, 500, 0, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Jelly Tee stretch strength")
MACRO_CONFIG_INT(AeJellyTeeDuration, ae_jelly_tee_duration, 237, 20, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Jelly Tee smoothing duration")

MACRO_CONFIG_INT(AeFinishPrediction, ae_finish_prediction, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show predicted DDRace/KoG finish progress")
MACRO_CONFIG_INT(AeFinishPredictionShowTime, ae_finish_prediction_show_time, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show finish prediction time")
MACRO_CONFIG_INT(AeFinishPredictionMode, ae_finish_prediction_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Finish prediction mode: time left or finish time")
MACRO_CONFIG_INT(AeFinishPredictionMilliseconds, ae_finish_prediction_milliseconds, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show centiseconds in finish prediction")
MACRO_CONFIG_INT(AeFinishPredictionPercentage, ae_finish_prediction_percentage, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show progress percentage in finish prediction")
MACRO_CONFIG_INT(AeFinishPredictionShowAlways, ae_finish_prediction_show_always, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show finish prediction even before a stable estimate exists")
MACRO_CONFIG_INT(AeFinishPredictionOffsetX, ae_finish_prediction_offset_x, 0, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Finish prediction horizontal offset from the upper center")
MACRO_CONFIG_INT(AeFinishPredictionOffsetY, ae_finish_prediction_offset_y, 58, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Finish prediction vertical offset from the top")
MACRO_CONFIG_INT(AeFinishPredictionScale, ae_finish_prediction_scale, 100, 50, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Finish prediction HUD size")

MACRO_CONFIG_INT(AeNinjaTimer, ae_ninja_timer, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show a compact DDRace ninja duration timer")
MACRO_CONFIG_INT(AeNinjaTimerOffsetX, ae_ninja_timer_offset_x, 0, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Ninja timer horizontal offset from the upper center")
MACRO_CONFIG_INT(AeNinjaTimerOffsetY, ae_ninja_timer_offset_y, 86, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Ninja timer vertical offset from the top")
MACRO_CONFIG_INT(AeNinjaTimerScale, ae_ninja_timer_scale, 100, 50, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Ninja timer HUD size")

MACRO_CONFIG_INT(AeTimerPanel, ae_timer_panel, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show Aether timer panel when the music player HUD is disabled")
MACRO_CONFIG_INT(AeTimerPanelOffsetX, ae_timer_panel_offset_x, 0, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether timer panel horizontal offset from the upper center")
MACRO_CONFIG_INT(AeTimerPanelOffsetY, ae_timer_panel_offset_y, 2, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether timer panel vertical offset from the top")
MACRO_CONFIG_INT(AeTimerPanelScale, ae_timer_panel_scale, 100, 50, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether timer panel HUD size")

MACRO_CONFIG_INT(AeTeamLastOverlay, ae_team_last_overlay, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show modern Aether last alive overlay")
MACRO_CONFIG_STR(AeTeamLastText, ae_team_last_text, 32, "LAST", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Text shown by the Aether last alive overlay")
MACRO_CONFIG_COL(AeTeamLastColor, ae_team_last_color, 0xFF6C4D, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether last alive overlay text color")
MACRO_CONFIG_INT(AeTeamLastBackground, ae_team_last_background, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show a background panel behind the Aether last alive overlay")
MACRO_CONFIG_INT(AeTeamLastOffsetX, ae_team_last_offset_x, 0, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Last alive overlay horizontal offset from the upper center")
MACRO_CONFIG_INT(AeTeamLastOffsetY, ae_team_last_offset_y, 34, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Last alive overlay vertical offset from the top")
MACRO_CONFIG_INT(AeTeamLastScale, ae_team_last_scale, 100, 50, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Last alive overlay size")
MACRO_CONFIG_INT(AeTeamFreezeCounter, ae_team_freeze_counter, 2, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show modern Aether team counter: 0 off, 1 alive, 2 frozen")
MACRO_CONFIG_COL(AeTeamFreezeCounterColor, ae_team_freeze_counter_color, 0xA9D7FF, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether team counter text color")
MACRO_CONFIG_INT(AeTeamFreezeCounterBackground, ae_team_freeze_counter_background, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show a background panel behind the Aether team counter")
MACRO_CONFIG_INT(AeTeamFreezeCounterOffsetX, ae_team_freeze_counter_offset_x, 0, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Team counter horizontal offset from the upper center")
MACRO_CONFIG_INT(AeTeamFreezeCounterOffsetY, ae_team_freeze_counter_offset_y, 18, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Team counter vertical offset from the top")
MACRO_CONFIG_INT(AeTeamFreezeCounterScale, ae_team_freeze_counter_scale, 100, 50, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Team counter overlay size")
MACRO_CONFIG_INT(AeTeamInvitePopup, ae_team_invite_popup, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show Aether team invite popup")
MACRO_CONFIG_INT(AeTeamInviteHideInTeam, ae_team_invite_hide_in_team, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide Aether team invite popup when already in a DDNet team")
MACRO_CONFIG_INT(AeTeamInviteHideRunning, ae_team_invite_hide_running, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide Aether team invite popup while the local tee is running")
MACRO_CONFIG_INT(AeTeamInviteBindMigrated, ae_team_invite_bind_migrated, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Internal migration flag for team invite join bind")
MACRO_CONFIG_INT(AeTeamInvitePopupOffsetX, ae_team_invite_popup_offset_x, 8, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Team invite popup horizontal offset from the left")
MACRO_CONFIG_INT(AeTeamInvitePopupOffsetY, ae_team_invite_popup_offset_y, 8, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Team invite popup vertical offset from the top")
MACRO_CONFIG_INT(AeTeamInvitePopupScale, ae_team_invite_popup_scale, 100, 50, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Team invite popup HUD size")
MACRO_CONFIG_INT(AeTeamLastWarningVisual, ae_team_last_warning_visual, 0, 0, 3, CFGFLAG_CLIENT, "Legacy unused Aether last warning visual mode")
MACRO_CONFIG_INT(AeVotePanel, ae_vote_panel, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show modern Aether vote panel")
MACRO_CONFIG_INT(AeVotePanelOffsetX, ae_vote_panel_offset_x, 6, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Vote panel horizontal offset from the left")
MACRO_CONFIG_INT(AeVotePanelOffsetY, ae_vote_panel_offset_y, 54, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Vote panel vertical offset from the top")
MACRO_CONFIG_INT(AeVotePanelScale, ae_vote_panel_scale, 100, 50, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Vote panel HUD size")

MACRO_CONFIG_INT(Ae3DParticles, ae_3d_particles, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw layered Aether 3D ambient particles")
MACRO_CONFIG_INT(Ae3DParticlesCount, ae_3d_particles_count, 60, 0, 180, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether 3D particle count")
MACRO_CONFIG_INT(Ae3DParticlesType, ae_3d_particles_type, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether 3D particle type: cube, heart or mixed")
MACRO_CONFIG_INT(Ae3DParticlesSize, ae_3d_particles_size, 8, 2, 28, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether 3D particle size")
MACRO_CONFIG_INT(Ae3DParticlesSpeed, ae_3d_particles_speed, 18, 0, 120, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether 3D particle drift speed")
MACRO_CONFIG_INT(Ae3DParticlesRotationSpeed, ae_3d_particles_rotation_speed, 35, 0, 120, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether 3D particle rotation speed")
MACRO_CONFIG_INT(Ae3DParticlesAlpha, ae_3d_particles_alpha, 35, 1, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether 3D particle opacity")
MACRO_CONFIG_INT(Ae3DParticlesColorMode, ae_3d_particles_color_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether 3D particle color mode: custom or random")
MACRO_CONFIG_COL(Ae3DParticlesColor, ae_3d_particles_color, 0xFFFFFF, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether 3D particle custom color")
MACRO_CONFIG_INT(Ae3DParticlesGlow, ae_3d_particles_glow, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Add subtle glow to Aether 3D particles")

MACRO_CONFIG_INT(AeSettingsScale, ae_settings_scale, 100, 80, 140, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether settings page scale")
MACRO_CONFIG_INT(AeGradientTeamColors, ae_gradient_team_colors, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use gradient DDRace team backgrounds in the scoreboard")
MACRO_CONFIG_INT(AeGradientNicknames, ae_gradient_nicknames, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Experimental gradient nickname colors")
MACRO_CONFIG_COL(AeGradientNicknameStartColor, ae_gradient_nickname_start_color, 0x64C8FF, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Gradient nickname start color")
MACRO_CONFIG_COL(AeGradientNicknameEndColor, ae_gradient_nickname_end_color, 0xFF7BDA, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Gradient nickname end color")
MACRO_CONFIG_INT(AeGradientNicknameGlow, ae_gradient_nickname_glow, 20, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Gradient nickname glow intensity")
MACRO_CONFIG_INT(AeGradientNicknameAnimated, ae_gradient_nickname_animated, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Animate experimental gradient nickname color")
MACRO_CONFIG_INT(AeGradientNicknameSpeed, ae_gradient_nickname_speed, 35, 1, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Gradient nickname animation speed")
MACRO_CONFIG_INT(AeGradientNicknameStyle, ae_gradient_nickname_style, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Gradient nickname effect style: 0 none, 2 sparkles")

MACRO_CONFIG_INT(AeGameChessShowLegalMoves, ae_game_chess_show_legal_moves, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show legal move hints in Aether Chess")
MACRO_CONFIG_INT(AeGameSnakeFieldSize, ae_game_snake_field_size, 16, 10, 24, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether Snake field size")
MACRO_CONFIG_INT(AeGameSnakeStartSpeed, ae_game_snake_start_speed, 4, 1, 8, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether Snake start speed")
MACRO_CONFIG_INT(AeGameSnakeWrap, ae_game_snake_wrap, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Allow Aether Snake to wrap through walls")
MACRO_CONFIG_INT(AeGameMinesweeperDifficulty, ae_game_minesweeper_difficulty, 1, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether Minesweeper difficulty")
MACRO_CONFIG_INT(AeGameTetrisStartSpeed, ae_game_tetris_start_speed, 3, 1, 8, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether Tetris start speed")

MACRO_CONFIG_INT(AeBrowserUtils, ae_browser_utils, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Aether server browser utilities")
MACRO_CONFIG_INT(AeBrowserAutoRefresh, ae_browser_auto_refresh, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Automatically refresh the active server browser tab")
MACRO_CONFIG_INT(AeBrowserRefreshSeconds, ae_browser_refresh_seconds, 30, 5, 120, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Server browser auto-refresh interval")
MACRO_CONFIG_INT(AeBrowserShortKoGNames, ae_browser_short_kog_names, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Shorten KoG server names in the browser list")

MACRO_CONFIG_INT(AeMapBgGradientType, ae_map_bg_gradient_type, 0, 0, 3, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether map background gradient type: vertical, horizontal, diagonal or radial")
MACRO_CONFIG_INT(AeMapBgAngle, ae_map_bg_angle, 0, -180, 180, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether map background gradient angle")
MACRO_CONFIG_COL(AeMapBgTopColor, ae_map_bg_top_color, 0x0A2D52, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether map background first color")
MACRO_CONFIG_COL(AeMapBgBottomColor, ae_map_bg_bottom_color, 0x1C102C, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether map background second color")
MACRO_CONFIG_COL(AeMapBgAccentColor, ae_map_bg_accent_color, 0x1F8EA8, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether map background accent color")
MACRO_CONFIG_INT(AeMapBgBrightness, ae_map_bg_brightness, 100, 40, 160, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether map background brightness percent")
MACRO_CONFIG_INT(AeMapBgContrast, ae_map_bg_contrast, 100, 40, 180, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether map background contrast percent")
MACRO_CONFIG_INT(AeMapBgSaturation, ae_map_bg_saturation, 100, 0, 180, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether map background saturation percent")
MACRO_CONFIG_INT(AeMapBgVignette, ae_map_bg_vignette, 16, 0, 80, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether map background edge darkening percent")
MACRO_CONFIG_STR(AeMapBgExportName, ae_map_bg_export_name, 64, "aether_bg", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether map background export map name")
MACRO_CONFIG_STR(AeMapBgImage, ae_map_bg_image, 128, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "PNG from assets/backgrounds embedded into the Aether map background")
MACRO_CONFIG_INT(AeCustomBackground, ae_custom_background, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use the Aether generated custom entities background")
MACRO_CONFIG_INT(AeMediaBackgroundGame, ae_media_background_game, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use selected media PNG as the entities game background")
MACRO_CONFIG_STR(AeMediaBackgroundImage, ae_media_background_image, 128, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "PNG from assets/backgrounds used by Media Background")
MACRO_CONFIG_INT(AeMediaBackgroundMenu, ae_media_background_menu, 0, 0, 1, CFGFLAG_CLIENT, "Legacy unused media background menu toggle")
MACRO_CONFIG_INT(AeMediaBackgroundMapOffset, ae_media_background_map_offset, 0, -100, 100, CFGFLAG_CLIENT, "Legacy unused media background map offset")

MACRO_CONFIG_INT(AeCustomResolution, ae_custom_resolution, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use a custom logical game aspect ratio without resizing the window")
MACRO_CONFIG_INT(AeCustomResolutionWidth, ae_custom_resolution_width, 1877, 640, 7680, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether custom window width")
MACRO_CONFIG_INT(AeCustomResolutionHeight, ae_custom_resolution_height, 937, 360, 4320, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aether custom window height")
MACRO_CONFIG_INT(AeSaveUnsentMessages, ae_save_unsent_messages, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Restore unsent chat drafts after closing chat or reconnecting")

MACRO_CONFIG_INT(AeRollbackDemo, ae_rollback_demo, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Keep the replay recorder ready for rollback demo clips")
MACRO_CONFIG_INT(AeRollbackDemoSeconds, ae_rollback_demo_seconds, 30, 10, 600, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Seconds saved by ae_save_rollback_demo")

MACRO_CONFIG_INT(AeAimTraining, ae_aim_training, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Aether aim training overlay")
MACRO_CONFIG_INT(AeAimTrainingTargets, ae_aim_training_targets, 1, 1, 8, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Number of active aim training targets")
MACRO_CONFIG_INT(AeAimTrainingTargetSize, ae_aim_training_target_size, 28, 8, 96, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aim training target size")
MACRO_CONFIG_INT(AeAimTrainingDistance, ae_aim_training_distance, 220, 64, 560, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum aim training target distance from your tee")
MACRO_CONFIG_COL(AeAimTrainingTargetColor, ae_aim_training_target_color, 0xF255C6FF, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Aim training target color")
MACRO_CONFIG_INT(AeAimTrainingDim, ae_aim_training_dim, 28, 0, 75, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aim training background dim amount")
MACRO_CONFIG_INT(AeAimTrainingShrink, ae_aim_training_shrink, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Shrink aim training targets after spawning")
MACRO_CONFIG_INT(AeAimTrainingShrinkMs, ae_aim_training_shrink_ms, 1200, 150, 10000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Milliseconds before a target reaches normal size")
MACRO_CONFIG_INT(AeAimTrainingDespawn, ae_aim_training_despawn, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Respawn aim training targets after a timeout")
MACRO_CONFIG_INT(AeAimTrainingDespawnMs, ae_aim_training_despawn_ms, 2500, 250, 10000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Milliseconds before an unhit target respawns")
MACRO_CONFIG_INT(AePsa, ae_psa, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable the Aether PSA helper")

MACRO_CONFIG_INT(AeOptimizer, ae_optimizer, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Aether optimizer options")
MACRO_CONFIG_INT(AeOptimizerHighPriority, ae_optimizer_high_priority, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Set the client process priority to high while running")
MACRO_CONFIG_INT(AeOptimizerDisableParticles, ae_optimizer_disable_particles, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Disable in-game particles")
MACRO_CONFIG_INT(AeOptimizerDisableMenuAnimations, ae_optimizer_disable_menu_animations, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Disable non-music menu and Aether settings animations")
MACRO_CONFIG_INT(AeOptimizerDiscordBelowNormal, ae_optimizer_discord_below_normal, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Set Discord process priority below normal while the optimizer is enabled")
MACRO_CONFIG_INT(AeOptimizerFpsFog, ae_optimizer_fps_fog, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Limit expensive map tile rendering around the camera")
MACRO_CONFIG_INT(AeOptimizerFpsFogCullTiles, ae_optimizer_fps_fog_cull_tiles, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Cull map tiles outside the FPS fog radius")
MACRO_CONFIG_INT(AeOptimizerFpsFogRenderRect, ae_optimizer_fps_fog_render_rect, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Render the FPS fog radius rectangle")
MACRO_CONFIG_INT(AeOptimizerFpsFogRadius, ae_optimizer_fps_fog_radius, 20, 6, 160, CFGFLAG_CLIENT | CFGFLAG_SAVE, "FPS fog manual radius in tiles")
